title: AcceleraFPGA
description: AcceleraFPGA is a collaborative ecosystem that seamlessly integrates FPGA hardware with modern software stacks to enable low-latency, high-performance solutions for compute-intensive workflows. Designed for industries like semiconductor design, defence, fintech, and AI/ML.
theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0

# Enable all the plugins
plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links

# Plugin settings
paginate: 5
optional_front_matter:
  remove_originals: true
readme_index:
  enabled: true
  remove_originals: true
titles_from_headings:
  enabled: true
  strip_title: true
relative_links:
  enabled: true
  collections: true

# GitHub metadata settings
repository: nik-dev-sketch/AcceleraFPGA
